### ISSUE TITLE
vqmod not replacing in OC 3+

### ISSUE THREAD

**Issue by nikto1** [vqmod/vqmod#112]
I did some tests with some ocmod scripts active. If some ocmod is targeting e.g. the "`</head>`" tag, then the vqmod doesn't replace, ecc. anymore. If i disable all ocmod scripts, vqmod is working fine.
However the *.cache files are created but the vqcache is empty. In the above example the header.twig file won't be generated.

**Comment by qphoria** [comment]
I think this is because currently ocmods can't modify twig files.. but
"thinks" it can..This results in an empty file
Since vQmod applies itself AFTER ocmods, it is getting that empty file and
can't match.
So the bug is in ocmod, but trickles downstream to vQmod.

The fix is to wait for ocmod to support twig files.. and don't use ocmods
with twig modifications because they don't work.
Or just always use vQmods because we always work :)

Qphoria

**Comment by nikto1** [comment]
Ocmod does actually replace stuff in .twig files, but with active ocmod files VQmod stops to work.
I'm aware of using ocmod, but others are using it. 
If you have a couple of ocmods in a shop, then VQmod stops to work and people are complaining.
Obviously an OC enduser have no idea about what's going on.
Sorry for saying that, but OC is getting a bit messy. I'm out of ideas...

**Comment by qphoria** [comment]
Is it only with ocmodded twig files that it fails? or all ocmodded files?

**Comment by nikto1** [comment]
VQmod stops to apply the modifications for .twig files if you have active an ocmod modification in an OC-shop and with this OCmod file (modification) you target the same tag or whatever, maybe also only the same file.
E.g. i had a shop where an OCmod script targets the "`</head>`" tag in the common/header.twig file. 
My VQmod file is targeting the same tag ("`</head>`") and my script won't work because of OCmod.

Now, you cannot tell customers to switch to VQmod or viceversa. Hope i explained the situation

**Comment by qphoria** [comment]
Ok I understand and have found the issue. I was not aware that ocmod could do twig files because it wasn't using the normal method for other files. So we've adapted the vqmod to work with it now. Just a small change the vqmod_opencart.xml file

[vqmod_opencart.txt](https://github.com/vqmod/vqmod/files/1153462/vqmod_opencart.txt)

Rename this from .txt to .xml and it upload to vqmod/xml and it should work with ocmodded twigs

**Comment by nikto1** [comment]
Great thanks, will test it, then i'll let you know

**Comment by nikto1** [comment]
Working now...
