### ISSUE TITLE
Retarded pissheads - redirecting to a malware in the installation guide

### ISSUE THREAD

**Issue by TomPissed** [vqmod/vqmod#131]
What a fucked up application, redirecting their interested users to a malware site... great.

**Comment by qphoria** [comment]
Umm? Hi?
What are we talking about ?

**Comment by IP-CAM** [comment]
probably a simple pre-christmas depression, or then, in the wrong place.

**Comment by qphoria** [comment]
Well someone is getting coal in their stocking this year.

**Comment by TomPissed** [comment]
4.Goto http://www.yoursite.com/vqmod/install
The link gets you to a malware site. Maybe [your site URL]/vqmod/install would make more sense...

Can be found at https://github.com/vqmod/vqmod/wiki/Installing-vQmod-on-OpenCart

Have fun...

Hey, nothing wrong with some charcoal - cleans the stomach ;-)

**Comment by qphoria** [comment]
LMFAO! Here's the thing though.. if you didn't get that "yoursite.com" was meant to imply "your own site"...  you absolutely deserve to get a virus.

**Comment by osworx** [comment]
@TomPissed LMKYITA
People like you should go underground, throw the key to the door for it away - and never come back.

**Comment by qphoria** [comment]
LOL nah he's probably a good guy... a little extreme to call it "fucked up application" just because of a simple generic url. A lot of people prefer "www.example.com" on sites like stack overflow.. but who knows if that ever gets hacked... Tom will have a field day with it.

Merry Christmas Tom.. We will discuss updating the generic url with something even more fool proof.

**Comment by osworx** [comment]
Maybe tompissed.com ?

**Comment by IP-CAM** [comment]
Well, who fails on this already, won't get anywhere, most of the time, and one can't please 'em all. That's one thing I've learned, during my oc-attendance, among a few others...  :)
