### ISSUE TITLE
Big file - checked.cache

### ISSUE THREAD

**Issue by faca5** [vqmod/vqmod#157]
Hello.

We have problem with latest version of OpenCart v3.0.3.2 and VqMOD 2.6.4 with PHP 7.4.

File "checked.cache" keep growing each time user visit site.

We haven't this problem with OpenCart v2.0.3.2.

This problem we have already detected on different OpenCart version and webhosting.

Any idea how to solve?

Thank you.

**Comment by IP-CAM** [comment]
How many decades will it take, until the last Dino's accepted, that VqMod has been replaced by OcMod, Years ago. But if one really still want's to play the double-murder Game, JNeuhoff created an integrated VqMod, acting similar to OcMod, so avoiding to fill up VqCache.

**Comment by osworx** [comment]
1. this here is NOT the place to talk about 3PD extensions or something else ..
2. VQMod has its own bug list: https://github.com/vqmod/vqmod/issues
3. read this Forums thread: https://forum.opencart.com/viewtopic.php?f=183&t=165423 
4. expecially this here (how this bug can be solved): https://forum.opencart.com/viewtopic.php?f=183&t=165423&start=20

Doing so as bespoken under # 4, you can have the storage folder outside the public folders and no need to fiddle around  ..

And yes, using VQMod nowadays is that something "out of fashion".
The argument thta OCMod has not enough features maybe valid, but together with events no need to usw VQMod anymore.
The more as the creators of VQMod wether updating their module nor listening/answering the issue list or pull requests .. (e.g. jay6390)!

**Comment by IP-CAM** [comment]
Whatever, Events, OcMod, or VqMod, it won't keep OC from rapidly loosing on attractivity and Friends. It's forum is ruled by a self-proclaimed Cop, filling up the place with ever the same nonsense Replies, probably, just to add Numbers, and the amount of GITHUB Contributors, still willing, to assist, is nearly by zero. It started up with that unfamous OcMod Implementation, and it kept on, by changing to Twig, probably expecting, to so generate a new bread of Users and Dev's. And the Boss already dreams about the 'next' Version Changes, instead of better concentrating on the present last Release. 

I'm just glad, not to have been following the band-waggon. But those, depending on Income, have not much choice, but keep on playing the Game, regardless of, what Rules and Rulers exist. It's their own fault, to depend on something, just about as undepedable as the weather.... 

Sorry, it really does not belong here, I'm aware of that.
