### ISSUE TITLE
Will there be an update for OC4?

### ISSUE THREAD

**Issue by stalker780** [vqmod/vqmod#165]
OC4 have been released.

Is there any chance for a VQMod update?

Basically 2.6.6 works fine with applied twig patch.

```
<!-- fix vqmod 2.6.6 twig  -->
	<file name="system/library/template/twig.php">
		<operation>
			<search position="before" trim="true"><![CDATA[
				$twig = new
			]]></search>
			<add trim="true"><![CDATA[
				$file = \VQMod::modCheck($file);
				$file = str_replace(realpath(DIR_APPLICATION . '../'), '', $file);
				$file = trim(str_replace('\\', '/', $file), '/ ');
			]]></add>
		</operation>
	</file>
```

But OC4 allows renaming admin folder. I suspect VQMod needs some core changes to replace `admin/` file paths.

**Comment by IP-CAM** [comment]
Just to mention it, a VqMod Manager for OC v.4 already exists:
https://github.com/IP-CAM/VqMod-Manager-for-Opencart-v.4.x

**Comment by JAY6390** [comment]
> OC4 have been released.
> 
> Is there any chance for a VQMod update?
> 
> Basically 2.6.6 works fine with applied twig patch.
> 
> ```
> 
> 	<file name="system/library/template/twig.php">
> 		<operation>
> 			<search position="before" trim="true"><![CDATA[
> 				$twig = new
> 			]]></search>
> 			<add trim="true"><![CDATA[
> 				$file = \VQMod::modCheck($file);
> 				$file = str_replace(realpath(DIR_APPLICATION . '../'), '', $file);
> 				$file = trim(str_replace('\\', '/', $file), '/ ');
> 			]]></add>
> 		</operation>
> 	</file>
> ```
> 
> But OC4 allows renaming admin folder. I suspect VQMod needs some core changes to replace `admin/` file paths.

We've had the ability to change your admin folder easily since version 2.x. There is a file called "pathReplaces.php" that allows you to do that with just one line of code

@qphoria Are you able to release a version for v4.x to work too?

Kind regards
Jay

**Comment by qphoria** [comment]
I will take a look at OC4 this week and do some testing on it. 

> Because admin folder can be taken only from DIR_APPLICATION in admin/config.php. But if folder is renamed there is no way to automatically detect correct folder name.

We've intentionally kept a layer separation between vQmod and the source platform, but as the pathReplaces file is still a php file you can use
```
// START REPLACES //
if (defined('DIR_CATALOG')) {
	$replaces[] = array('~^admin\b~', basename(DIR_APPLICATION));
}
// END REPLACES //
```
and that will work as DIR_CATALOG is only defined in the admin/config.php file.

Perhaps with the opencart version we can pre-define that conditional within the pathReplaces.php file and that should make it automatic

**Comment by FelipoAntonoff** [comment]
Very good, also looking forward to vQmod in Opencart 4 :), going back to the origins of Opencart 1.5 with vQmod which to this day is a future proof tool and which also gave rise to OCMOD in Opencart 3 and 2.

I even opened a topic to see if they come back with OCMOD/vQmod in Opencart 4: https://github.com/opencart/opencart/discussions/10883, because I honestly don't think Events serves as a 100% replacement even for being a realtime tool which handles trigger and no cache.

@ taking the opportunity to thank you, vQmod was and is an excellent tool, it helped to make Opencart an even better platform and made it much easier to create Modules, which before would be done by changing directly in the files and with vQmod we simply make a simple XML that makes all the magic :)

If you need help with testing or some part of the code I can help. I will use it in our Codemarket modules for Opencart 4.

**Comment by JAY6390** [comment]
@FelipoAntonoff Qphoria has already released a version for OpenCart 4. You can find it here: https://github.com/vqmod/opencart - Note that the installation is a little different now (two uploads) as the opencart specific version has been split off from the vqmod engine itself
