### ISSUE TITLE
Install doco

### ISSUE THREAD

**Issue by PhilHudson** [vqmod/vqmod#28]
OK, found your install doco *by going to another site and following links from there*.

Now, please: use the 
```
code formatting
``` 
facility of Markdown on your instructions so I can have at least a little confidence in them. Finding that there's a newline missing in the *very first line* really knocks that confidence.

Sorry if I'm coming across as mean and angry, but really this is very very basic stuff.

**Comment by qphoria** [comment]
What exactly are you taking about?

**Comment by qphoria** [comment]
https://github.com/vqmod/vqmod/wiki

Couldn't be clearer. But lets get things straight. Wiki markdown is shit. bbcode would have been perfectly sufficient. No nobody can agree on a frickin syntax and it's a nightmare to remember which works where. Also this was moved from googlecode and some of the formatting gets lost. We are not impressed that you are a github markdown expert.. in fact we feel bad for you.

**Comment by qphoria** [comment]
Ok after much dicking around, We found the code markdown... which is humorously neither of the 2 options that github offers. Their editor notes say that 4 spaces or a tab will make code. That does nothing. Then if you click the <> button it adds a single backtick before and after the line, which does highlight it gray, but doesn't keep line breaks and doesn't do a codeblock. Instead we had to guess stackexchange style markdown which is 3 backticks before and after, and that worked. So it's no wonder we didn't have it formatted since github doesn't even know what it should be. Not so basic afterall I guess.
