### ISSUE TITLE
modify aleardy modified file

### ISSUE THREAD

**Issue by curiousPup** [vqmod/vqmod#35]
i need to modify a file that has already been modified by another XML. in that case, where should I apply my XML changes, on original file or the vq cache file??

**Comment by JAY6390** [comment]
Always original

**Comment by curiousPup** [comment]
but i need to modify exactly the same line which was already modified.
for an instance, xml1 modifies A to B. but i need to modify A to C using my own xml.
in such case, what should i include in my search tag, A or B??

**Comment by JAY6390** [comment]
When this happens, you still need to use the original path. In this instance, vqmods apply in alphabetical order, so if yours is named after the first one, then you need to account for that. There are usually smart ways of coding vqmods so that they work regardless (such as if you have a line that sets a variable which has been modified, just find a line after that and put your modification there). Keep it simple, use as small a search text as possible; remember that the search will match partial line text, it doesn't have to be the whole line. However, its up to you to figure out how to do this based on the circumstances of your mod. Sometimes you need to just code a solution for a conflict. VQMods don't always match up perfectly

**Comment by opencarthelp** [comment]
My three commandments for writing vQmod scripts are:

1. Replace is evil. Avoid it at all costs.
2. One insert per function or method.
3. Unique naming conventions avoid collisions with other scripts.

They're not achievable 100% of the time but the more you follow them the more stable your script will be.

**Comment by qphoria** [comment]
I wouldn't say it is evil, it is the backbone fundamental of modification. But when using replace, be sure to replace the SMALLEST chunk required. Don't change full lines if you don't need to. Always try to use the "trim" for the <add> code so that the replaces are done inline and don't cause line breaks in the middle of a string. You should definitely avoid using Replace with offset as that can indeed be evil.

**Comment by JAY6390** [comment]
I have to agree with @opencarthelp on this one @qphoria - replace should be the very last method you use after exhausting all other possibilities

**Comment by qphoria** [comment]
If I understand you correctly.. .

Lets say we are changing
$var = '123';
to
$var = 'abc';

Instead of
<search position="replace">123</search>
<add trim="true">abc</add>

You would do:
<search position="after">$var = '123';</search>
<add trim="true">$var = 'xyz';</add>

therefore double defining the variable and overriding it?

It's ok but a little impractical. It might allow other scripts to not fail, but those scripts would still be overridden and probably more confusing as to why the value isn't correct. At least with a hard error you know some other script has changed it and the line can't have 2 mods for the same exact spot.

**Comment by opencarthelp** [comment]
I started rethinking how I wrote vQmod scripts a few months ago.  Evil is admittedly a *tad* bit of hyperbole but replace really does have significant down sides.

1. Replace makes architecture less predictable for other developers.  Object structures can be modified, method parameters and outputs changed, scope morphed, code flow altered.  With many thousands of vQmod scripts published we open up core functionality to modification in completely unpredictable ways.

2. Replace is vulnerable to change.  By using it we're dependent on how the core functions rather than how our own code does.

3. It increases the chance of collisions with other scripts.  You're put in a position of fighting over code with other mods.  Having to modify load order to get scripts working is a general example of that.

It's a far better strategy to decouple code from the core as much as possible.  Have vQmod act like a de facto event system; instead of a dedicated mediator running pre- or postprocess we just place the code inline.

It forces you to stop thinking tactically and start thinking strategically.  What exactly are we try to *do* with that SQL snippet?  How can we achieve that without being directly dependent on a line of core code?  Can I restructure the database to put the data inside its own table?

Those kinds of questions can really improve the structure of a script.

**Comment by EveryAuction** [comment]
Opencart, as example, does just NOT supply a decent 'range' of possible 'fixed anchors', doing nothing else, but acting as SUCH, in order to allow VqMod's, to be 'linked', to make 'em work, without the chance of breaking the system. 

At least, this is, what I guess, beeing the basic problem. Especially, since such 'fixed anchors' can even be replaced, by VqMods, and so not longer exist, virtually, for following VqMods, using such 'Markers', or whatever one likes to call 'em, to make them work.

So, basically, it takes a GENERAL Routine, setting up and virtually place such MARKERS, in a DEFAULT Version Software, then, use those DEFAULT Markers, to 'enable' all following VqMod Routines and Tasks.

Just an idea, for some time, already...
Ernie

**Comment by opencarthelp** [comment]
That's the beauty of the no-replace method is.  Our inserts are binding to entry and exit points in the code which are fairly stable.

Add some preprocessing to your page controller with:

```xml
<search position="after"><![CDATA[
  public function index(
]]></search>
```

Add postprocessing by jumping in before the view is loaded:

```xml
<search position="before"><![CDATA[
  file_exists(DIR_TEMPLATE . $this->config->get('config_template') . '/template/common/cart.tpl')
]]></search>
```

Push your own model methods with:

```xml
<search position="after"><![CDATA[
  class ModelCatalogCategory extends Model {
]]></search>
```

There are only a few caveats:

1. OpenCart doesn't always have good separation of concerns. It's common to find chunks of code which should be their own methods jammed in the middle of a controller.  You're either doing multiple inserts or repeating a whole bunch of operations.

2. The model in general is tough to hook into for postprocessing.  It reuses variables names so you end up with a half-dozen instances of code like ```return $query->rows;```.

3. Doesn't work for templates.  DOM as a whole really isn't compatible with vQmod.

**Comment by JAY6390** [comment]
The one benefit of OC2 is that it has the actual hook system, which means you can hook into most model methods well both before and after data is manipulated, but yeah 1.5.X is a bit of a nightmare for it

**Comment by opencarthelp** [comment]
I've looked at rewriting/expanding the event system to make it something useful but it would have ended up rewriting a huge chunk of OpenCart's core.  It's sort of a sad reminder of what could have been.

**Comment by qphoria** [comment]
I do agree with this process. All my mods always use "function index" as
the anchor and new functions either go before or if I want to set it up in
the index, I'll use after.
