### ISSUE TITLE
cannot redeclare loader::__get() in vqmod\vqcache\vq2_sysytem_engine_loader.php on line 22 error

### ISSUE THREAD

**Issue by varsha63** [vqmod/vqmod#45]
when i installed vqmod its work fine after install multimerch_marketplace  i get this error 

i m using opencart 1.5.6 version  and multimerch marketplace version is 3 is this a version problem or anything else 

please give me brief description

**Comment by JAY6390** [comment]
Not VQMod Engine specific. This is a bug with MultiMerch

**Comment by varsha63** [comment]
ok can u pls help me out after installing now i am getting

 oc_ms_product doesn't exist

select count (*) as total from oc_product left join oc_ms_product ms using
(product_id ) left join oc_ms_seller ms using (seller_id ) where 1=1 and
status = 1 in c:\wamp\www\system\database\mysql.php on line 50



and whole website blocked i m working on localhost right now

**Comment by PeteAUK** [comment]
You've not installed MultiMerch correctly so it's missing the database tables - I'm guessing you've just dragged it in and not done everything.  Follow the installation instructions fully and pay attention to:
Install MultiMerch via Admin > Extensions > Modules > [MultiMerch] Digital Marketplace. This step is mandatory as it creates the database tables required for MultiMerch to function correctly and skipping it will lead to errors.

**Comment by varsha63** [comment]
when i done myurl/vqmod/install i having vqmod success msg but xml file i
include in vqmod/xml folder not working on server.


when i click on edit i got


*Fatal error*: Class 'ControllerMultisellerBase' not found in
*/home/vikas140/public_html/admin/controller/module/multiseller.php* on
line *3*


*above mention error *

*what to do i need this extension to run.. *



*its working on localhost fine*


*ans asap *

**Comment by PeteAUK** [comment]
Varsha - you need to follow the installation instructions for MultiMerch not VQMod!  The problem is 100% related to the installation of the extension not VQMod.

If it's working on localhost and not live, then ensure you've a) copied over all of the files and b) installed it fully or replicated the database changes from localhost to live.

Head over to: http://www.opencart.com/index.php?route=extension/extension/info&extension_id=18376&filter_search=multimerch and contact the extension author if you've any further issues.

**Comment by JAY6390** [comment]
Use the multimerch forums to figure this out. We don't offer any support for third party applications/vqmods
