### ISSUE TITLE
vQmod and add-on domains

### ISSUE THREAD

**Issue by speeke** [vqmod/vqmod#79]
Hello,

I am trying to install vQmod on an add-on domain.

I originally installed it, and it appeared to be OK, but it did not generate any vqmod/vqcache or vqmod/logs folders or files.

The readme file states that the folder needs to be uploaded to the root, but I cannot upload to the parent domain root because the OpenCart installation is located on the add-on domain.

I will be looking to create multi-cart options (via other add-on domains) with OpenCart in the future, so I would like to be able to access the vQmod installation from all multi-carts.

I'm wondering if I should install OpenCart in the parent domain instead, so I can install vQmod, and then somehow redirect the url to the add-on domain??? If so, how would I do this, and then also create other add-on domains for the other multi-cart options in the future?

Any help you may be able to provide is very much appreciated?

**Comment by qphoria** [comment]
Root of your store, not of the server. Root is the same place as where the
index.php of the store will be

Q

Hello,

I am trying to install vQmod on an add-on domain.

I originally installed it, and it appeared to be OK, but it did not
generate any vqmod/vqcache or vqmod/logs folders or files.

The readme file states that the folder needs to be uploaded to the root,
but I cannot upload to the parent domain root because the OpenCart
installation is located on the add-on domain.

I will be looking to create multi-cart options (via other add-on domains)
with OpenCart in the future, so I would like to be able to access the vQmod
installation from all multi-carts.

I'm wondering if I should install OpenCart in the parent domain instead, so
I can install vQmod, and then somehow redirect the url to the add-on
domain??? If so, how would I do this, and then also create other add-on
domains for the other multi-cart options in the future?

Any help you may be able to provide is very much appreciated?

—
Reply to this email directly or view it on GitHub
<https://github.com/vqmod/vqmod/issues/79>.

**Comment by speeke** [comment]
Thank you for your reply. I did this, and I got the installation OK message, but but it did not
generate any vqmod/vqcache or vqmod/logs folders or files.

**Comment by speeke** [comment]
Thank you for your reply. I did this, and I got the installation OK message, but but it did not
generate any vqmod/vqcache or vqmod/logs folders or files.

**Comment by qphoria** [comment]
It won't generate vqcache files until you load the homepage at least once

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by speeke** [comment]
Hi Tom,

Thank you for helping me! There still seems to be a problem, and I’m not getting anywhere with it.

I tried installing the a module: ExtensionUninstaller (iSenseLabs - I’ve emailed them for help too, but no reply to date!)

But get the following error (I am using an add-on domain which is located in the root - the same location as the public_html folder, and I have recently installed vQmod):

===
SyntaxError: JSON Parse error: Unrecognized token '<'
OK
<b>Warning</b>: mkdir(): No such file or directory in <b>/home/micromil/mydomain.com.au/vqmod/vqcache/vq2-admin_controller_extension_installer.php <http://mydomain.com.au/vqmod/vqcache/vq2-admin_controller_extension_installer.php></b> on line <b>82</b><b>Warning</b>: move_uploaded_file(/home/micromil/mydomain.com.au/system/upload/temp-ZDQxOiQSGxImJPLNbzM1lDKFiomS5WNe/install.xml <http://mydomain.com.au/system/upload/temp-ZDQxOiQSGxImJPLNbzM1lDKFiomS5WNe/install.xml>): failed to open stream: No such file or directory in <b>/home/micromil/mydomain.com.au/vqmod/vqcache/vq2-a <http://mydomain.com.au/vqmod/vqcache/vq2-a>
===

The error log shows:

2016-02-29 17:59:38 - PHP Warning:  mkdir(): No such file or directory in /home/micromil/mydomain.com.au/vqmod/vqcache/vq2-admin_controller_extension_installer.php on line 82
2016-02-29 17:59:38 - PHP Warning:  move_uploaded_file(/home/micromil/mydomain.com.au/system/upload/temp-iNpY2pQpACduJnmMJJvzUOSWbJk7VZrF/install.xml): failed to open stream: No such file or directory in /home/micromil/mydomain.com.au/vqmod/vqcache/vq2-admin_controller_extension_installer.php on line 93
2016-02-29 17:59:38 - PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpTtCPXI' to '/home/micromil/mydomain.com.au/system/upload/temp-iNpY2pQpACduJnmMJJvzUOSWbJk7VZrF/install.xml' in /home/micromil/mydomain.com.au/vqmod/vqcache/vq2-admin_controller_extension_installer.php on line 93

Can you please help?

Thank you very much,
Sarah

**Comment by qphoria** [comment]
Set me up with ftp access and I'll take a look
Email me directly @ qphoria - at- g mail dott com
don't reply to this email as it will post publicly.

Cheers,

Tom "Qphoria"
OpenCartGuru.com
