### ISSUE TITLE
Issues with Non-Allow Chars in Filenames on Windows

### ISSUE THREAD

**Issue by budgetneon** [vqmod/vqmod#81]
Trying to help someone on the opencart forums here:

http://forum.opencart.com/viewtopic.php?f=183&t=159432

Somehow, vqmod is trying to create a file with a name that has a colon (:) in it.   That won't work on Windows, as there are some characters [not allowed in a filename.](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#naming_conventions)

**Comment by qphoria** [comment]
That was a bug in 2.6.0. Get 2.6.1

**Comment by chrisdempsey** [comment]
It is 2.6.1 that's installed: $_vqversion = '2.6.1';

Any chance you could take a look through the Opencart forum post linked above and advise if you can point me in the right direction?

**Comment by budgetneon** [comment]
Basically, it's the call to realpath() that's introducing a colon back in...because realpath() returns things like 'C:\whatever\whatever' on windows.

**Comment by qphoria** [comment]
But I developed this on a windows machine and I do not have the same issue.

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by JAY6390** [comment]
What server are you running? IIS?

**Comment by chrisdempsey** [comment]
Experiencing issue on IIS8.

All versions up to 2.5.1 ran successfully on previous server with IIS7.5.

**Comment by chrisdempsey** [comment]
Think this is solved.

**Short version**
Changing line #120 of vqmod.php from

`$stripped_filename = preg_replace('~^' . preg_quote(self::getCwd(), '~i') . '~', '', $sourcePath)`

to

`$stripped_filename = preg_replace('~^' . preg_quote(self::getCwd(), '~i') . '~i', '', $sourcePath);`

Means the /vqmod/vqcache/vq2-*.php cache files are written and the website runs as normal.

**Long version**
Breaking down line #120:

* [list]self::getCwd() is returned as: C:\Net\hosts\domai... etc.
* $sourcePath is generated by self::_realpath($sourceFile); and is returned as: C:\net\hosts\domai... etc.
* function _realpath() sets $path = realpath($file);

So when preg_quote tries to create $stripped_filename it can't find an exact match because for case-insensitive filesystems [realpath()](http://php.net/manual/en/function.realpath.php) may or may not normalize the character case.

Since Windows is case insensitive I guess this is where the problem lies.

However, I am unsure why only the first letter in the path is affected.  

The absolute root directory is C:\Net which $sourcepath returns as C:\net.

If sub folders have upper case letters they are returned as such.

I guess the reason there was no issue on the original server is the absolute root directory happens to be C:\net.

I'll test further with additional sites tomorrow.

Can anyone advise how Linux systems would react to the change to line #120 noted above?  

I tested very briefly on a site on the old server and it looks to behave as normal.

I'm wondering if a pull request should be submitted?

**Comment by JAY6390** [comment]
Hi Chris

Don't have time to test this just now on a linux install, but from that line I notice the `i` you add may well need to be there, and the `i` in the preg_quote function defintely shouldn't be there (i.e. the first `~i` should be `~`

Kind regards
Jay

**Comment by qphoria** [comment]
Well I do use windows and don't see this problem, but I also don't use IIS.
Still this must be something new in IIS 8 as the vQmod code for realpath
hasn't changed in 2 years.
Then again.. if you are using IIS you should probably be taken out and shot
anyway

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by chrisdempsey** [comment]
The `i` in preg_quote was introduced in v2.4.1

$stripped_filename = preg_replace('~^' . preg_quote($this->getCwd(), '~') . '~', '', $sourcePath); // 2.3.2
$stripped_filename = preg_replace('~^' . preg_quote(self::getCwd(), '~i') . '~', '', $sourcePath); // 2.4.1

The `i` in preg_replace definitely needs to be there for my environment.

I assume it relates to IIS8 rather than PHP 5.3.29.  Will find out shortly as I need the sites running on PHP 5.4 or 5.5 to take advantage of Wincache.

If necessary, perhaps in future releases the `$windows` flag could be used to switch between patterns `'~'` and `'~i'`if Linux wasn't happy with it being a permanent feature.  Probably shouldn't be as it would cause the same problem in reverse if two directories existed with the same name and different case.

Or a note in the readme.txt in case anyone else is on IIS.

Was forced into IIS by an employer years ago. Now I'm too heavily invested in the platform to uproot.

**Comment by JAY6390** [comment]
Hmm, the `i` should be after the last `~`, i.e.

```
$stripped_filename = preg_replace('~^' . preg_quote(self::getCwd(), '~') . '~i', '', $sourcePath);
```

**Comment by chrisdempsey** [comment]
I only left the first `i` in because it's in the original code.

Guess it's possible the original author intended to place it after the last `~` but since Linux has a case sensitive filesystem I'm not sure they would deliberately make the `preg_replace` case insensitive.

Main thing this is documented now so anyone that experiences it on IIS in future might find the resolution quickly.

**Comment by JAY6390** [comment]
Hi Chris

Yeah I wrote the original and it definitely wasn't meant to be there - though how it's been overlooked for a couple of years I don't know :smile:. The insensitive was actually due to windows if I recall correctly and it's only on the cwd value so not all that important for sensitivity. The chances of someone having two directories with the exact same path but a case difference is very unlikely

**Comment by chrisdempsey** [comment]
I'm sure that'll be because I'm the only one running it on IIS.

Do you mind if I submit a pull request with the correction?  I've only contributed directly to one other repository so could use the practice.

**Comment by qphoria** [comment]
Yes give it a try. We could use the practice with pull merges as well :)

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by howdu** [comment]
I've been getting the same issue on windows the [opencart branch](https://github.com/vqmod/vqmod/tree/opencart) still references 2.6.0. Downloading 2.6.1 from tree fixed issue.

**Comment by susanlummis** [comment]
I am out of the office on annual leave, and will return on Monday 22nd May.  For urgent queries please email steve@puckator.co.uk
