### ISSUE TITLE
VQMod doesn't edit custom location

### ISSUE THREAD

**Issue by iReptile** [vqmod/vqmod#90]
I have a question I ran in to the same problem now for the second time and was wondering if this is a bug.

I want to use vqmod to edit a header file of a custom theme which is located in a subfolder.
Some how whatever I do no vqcache is made and no change is done.

I can use vqmod to make a change to:
catalog\view\theme\custom_theme\template\common\header.tpl

But not to:
catalog\view\theme\custom_theme\template\common\headers\header2.tpl (or any number of header file)

Why is this?

**Comment by susanlummis** [comment]
I am out of the office until the 12th July.  For urgent issues please contact steve@puckator.co.uk

**Comment by JAY6390** [comment]
@iReptile The reason is likely that whatever code is including the file is not running it through the `VQMod::modCheck()` method or the OpenCart `modification()` method

**Comment by iReptile** [comment]
Is there any way to fix this?
Or is it not possible to edited these files with these kind of themes?

**Comment by iReptile** [comment]
I think you are right because ocmod isn't making any changes eithet to those files.

**Comment by JAY6390** [comment]
If the template is loaded correctly, it would automatically be passed through ocmod and vqmod. Whatever method is loading that template is not a standard function of opencart. You'd need to find where that is and adjust it

**Comment by iReptile** [comment]
Ok thank you.

**Comment by qphoria** [comment]
To explain the actual issue a little better...
vQmod works on the principle that the controller, model, language, and theme files are loaded through the main router. When you see index.php?route=xxx/yyy that means that controller gets loaded in the router and we can intercept the file with the vQmod modcheck function. Controllers load template files. As long as the template file is loaded through the loader, it can be vQmodded/ocmodded. It's a sort of chain. But when theme makers break the conformity, and call their own include or require instead of loading it the correct way, then that breaks the chain.

The fix is to use vQmod to alter the last working part of the chain, the file that incorrectly calls the _headers_ files and change it to use a vQmod modcheck call.

Here's an example I had to use for the shoppica theme back in the day
```
<file name="catalog/view/theme/shoppica/template/product/product.tpl">
    <operation>
        <search position="replace"><![CDATA[
        <?php require 'product_options.tpl' ?>
        ]]></search>
        <add trim="true"><![CDATA[
        <?php require($vqmod->modCheck(DIR_SYSTEM . '../catalog/view/theme/shoppica/template/product/product_options.tpl')) ?>
        ]]></add>
    </operation>
</file>
```

Then after I did that I was able to make a vQmod call to that product_options.tpl file

```
<file name="catalog/view/theme/shoppica/template/product/product_options.tpl">
    <operation>
        <search position="before"><![CDATA[
        type="checkbox"
        ]]></search>
        <add><![CDATA[
	<?php $xyz = true; ?>
        ]]></add>
    </operation>
</file>
```

**Comment by iReptile** [comment]
Thanks I understand now.
I will try to make it work in the way you described.
