### ISSUE TITLE
ocMod files with multiple files in the "path" attribute don't work

### ISSUE THREAD

**Issue by ClearThinking** [vqmod/vqmod#95]
When using an ocMod in the /vqmod/xml/ folder, it works fine except when there are multiple files in the "path" attribute. For example:

<file path="catalog/controller/*/header.php|catalog/controller/*/footer.php">

This doesn't work with the ocMod delimiter ( | ) or the vQmod delimiter ( , ). Can you guys fix this when you have time?

**Comment by JAY6390** [comment]
Hey Johnathan. Can you provide an example of the comma delimited one you tried?

**Comment by nmpetkov** [comment]
This ocmod syntax does not work in vqmod:

```
<file path="catalog/view/theme/*/template/extension/module/{featured.tpl,latest.tpl,bestseller.tpl,special.tpl}">
```

:-(

**Comment by ChrisLancs** [comment]
You don't have the required **name** attribute, **path** is for the file path only so that you don't have to type out the path multiple times for multiple files under the same path. Not sure path works with wildcards but **name** does.

The options are
`<file path="path/to/file/" name="filename.ext">
or
<file name="path/to/file/filename.ext">
`

**Comment by JAY6390** [comment]
Path should work with wildcards just fine

**Comment by qphoria** [comment]
@nmpetkov 
This is true. We do not currently support their method of multiple files.
For vQmod it uses this format

`<file path="catalog/view/theme/*/template/extension/module/"
 name="featured.tpl,latest.tpl,bestseller.tpl,special.tpl">
`

We were looking into adding support for ocmod format but haven't yet.
