### ISSUE TITLE
vqmod DOMDocument missing in php5.6 issue 

### ISSUE THREAD

**Issue by Olamyy** [vqmod/vqmod#99]
I'm attempting to set up a store using opencart which i am honestly very new to. I bought a theme and for some reason the team uses vqmod. I was able to install the vqmod using:

> localhost/mystore/vqmod/install

and i get this response.

> VQMOD ALREADY INSTALLED!

Now, when i navigate to

> localhost/mystore

An error pops up saying

> DomDocument

The full error message is missing

> VQMod::bootup - ERROR - YOU NEED THE PHP "DOMDocument" EXTENSION INSTALLED TO USE VQMod

After a little research, i figured i had to install the php5.6-xml and php7.0-xml which i have.

However the error is still showing.

I went into the vqmod code and noticed the section raising the error is this.

```
if(!class_exists('DOMDocument')) {
        die('VQMod::bootup - ERROR - YOU NEED THE PHP "DOMDocument" EXTENSION INSTALLED TO USE VQMod');
    }
```
which means there's a DOMDocument class i'm missing.

However, i have tried everything i've seen online. From installing php-xml, purging php, installing php-dom,restarting apache2, checking phpinfo.

None of these seem to solve the issue.

How do i get the DOMDocument class?

**Comment by JAY6390** [comment]
Really not sure what to suggest. You need DOMDocument for VQMod to work. It sounds like you have installed it but not compiled php with the php-xml extension as part of it. I have both a 5.6 and a 7.0 install that use vqmod just fine, so the issue here is php and not vqmod. If you are using php fpm you may need to restart that. This question is better suited for a site like stack overflow
